# Generated by Django 3.2.2 on 2021-05-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_color',
            field=models.IntegerField(default=-1),
        ),
    ]
