# Generated by Django 3.2.2 on 2021-05-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_personal_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
